package bubbles.specialBubbles;

import utilz.LoadSave;
import entities.Player;
import levels.LevelManager;

import java.awt.*;
import java.util.LinkedList;
import java.awt.image.BufferedImage;

import static utilz.Constants.Bubble.*;
import static utilz.Constants.PlayerConstants.DEFAULT_H;
import static utilz.Constants.PlayerConstants.DEFAULT_W;

public class SpecialBubbleManager {

    // This class is responsible for managing the special bubbles (not generated by the player), such as waterBubble and fireBubble

    private static SpecialBubbleManager instance;
    private final Player player;

    private final LinkedList<SpecialBubble>  bubbles;
    private final LinkedList<WaterFlow> waterFlows;

    private BufferedImage[][] waterBubbleSprites;
    private BufferedImage[][] lightningBubbleSprites;
    private BufferedImage[][] playerSprites;

    private BubbleGenerator bubbleGenerator;

    private SpecialBubbleManager(Player player) {
        this.player = player;
        bubbles = new LinkedList<>();
        waterFlows = new LinkedList<>();

        loadBubbleSprites();
    }

    public static SpecialBubbleManager getInstance(Player player) {
        if (instance == null) {
            instance = new SpecialBubbleManager(player);
        }
        return instance;
    }

    public static SpecialBubbleManager getInstance() {
        return instance;
    }

    public void draw(Graphics g) {
        for (SpecialBubble b : bubbles) {
            if (b.isActive())
                b.draw(g);
        }

        for (WaterFlow w : waterFlows) {
            if (w.isActive())
                w.draw(g);
        }
    }

    public void update() {
        bubbleGenerator.update();

        for (SpecialBubble b : bubbles) {
            if (b.isActive()) {
                b.update();
                b.checkCollisionWithPlayer(player);
            }
        }

        for (WaterFlow w : waterFlows) {
            if (w.isActive()) {
                w.update();
                w.updateCollisions(player);
            }
        }
    }

    public void loadBubbleGenerator() {
        bubbleGenerator = LevelManager.getInstance().getCurrentLevel().getBubbleGenerator();
    }

    private void loadBubbleSprites() {
        waterBubbleSprites = new BufferedImage[2][1];
        BufferedImage temp = LoadSave.GetSprite(LoadSave.WATER_BUBBLE_SPRITE);
        waterBubbleSprites[0][0] = temp.getSubimage(0 , 0, DEFAULT_W, DEFAULT_H);
        waterBubbleSprites[1][0] = temp.getSubimage(DEFAULT_W , 0, DEFAULT_W, DEFAULT_H);

        lightningBubbleSprites = new BufferedImage[2][1];
        temp = LoadSave.GetSprite(LoadSave.LIGHTNING_BUBBLE_SPRITE);
        lightningBubbleSprites[0][0] = temp.getSubimage(0 , 0, DEFAULT_W, DEFAULT_H);
        lightningBubbleSprites[1][0] = temp.getSubimage(DEFAULT_W , 0, DEFAULT_W, DEFAULT_H);

        temp = LoadSave.GetSprite(LoadSave.PLAYER_SPRITE);
        playerSprites = new BufferedImage[6][7];
        for (int j = 0; j < playerSprites.length; j++)
            for (int i = 0; i < playerSprites[j].length; i++)
                playerSprites[j][i] = temp.getSubimage(i * DEFAULT_W, j* DEFAULT_H, DEFAULT_W, DEFAULT_H);
    }

    public void newLevelReset() {
        bubbles.clear();
        waterFlows.clear();
    }

    public void newPlayReset() {
        newLevelReset();
    }

    public void addBubble(SpecialBubble bubble) {
        bubbles.add(bubble);
    }

    public void addWaterFlow(WaterFlow waterFlow) {
        waterFlows.add(waterFlow);
    }

    public BufferedImage[][] getWaterBubbleSprites() {
        return waterBubbleSprites;
    }

    public BufferedImage[][] getLightningBubbleSprites() {
        return lightningBubbleSprites;
    }

    public int getActiveBubblesCount() {
        int count = 0;
        for (SpecialBubble b : bubbles) {
            if (b.isActive())
                count++;
        }
        return count;
    }

    public Image[][] getPlayerSprites() {
        return playerSprites;
    }
}
